data_one = int(input("Data1 : "))
data_two = int(input("Data2 : "))
print(data_one,"+",data_two,"=",data_one + data_two)
print(data_one,"-",data_two,"=",data_one - data_two)
print(data_one,"*",data_two,"=",data_one * data_two)
print(data_one,"/",data_two,"=",data_one / data_two)